made an example md for structure in release notes pages
shopware/release-notes pull request #1
Opened 2023-11-07 18:25 UTC by kermie

I made an example md for a possible structure in release note pages. Please ditch this PR if it is unsolicited or if the issue is already resolved.

2023-11-16 12:22 UTC, shyim commented on src/6.5.6.x/6.5.6.0.md
> +* from now on, Shopware needs the PHP library `bcmath` in order to function properly. You may install it with `$ apt install php-bcmath` on your linux machine. We already added it to our [system requ
why do we need bcmath?

2023-11-16 17:46 UTC, sushmangupta requested changes

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +We introduced a new queue `low_priority` additional to the already existing `async` queue. This queue can be used by plugins, to queue up messages which are not important in a short manner.
```suggestion
We introduced a new queue, `low_priority`, in addition to the already existing `async` queue. This queue can be used by plugins, to queue up messages which are not important in a short manner.
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +We introduced a new queue `low_priority` additional to the already existing `async` queue. This queue can be used by plugins, to queue up messages which are not important in a short manner.
What does in a short manner.

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +The `plugin:create` command now can generate also:
```suggestion
The `plugin:create` command now can generate:
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +The commands `system:update:prepare` and `system:update:finish` now use the regular kernel while updating Shopware. This fixes a lot of issues when plugins extended root components like Symfony Confi
```suggestion
The commands `system:update:prepare` and `system:update:finish` now use the regular kernel while updating Shopware. This fixes a lot of issues when plugins extend root components like Symfony Configuration or created themes.
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +Thanks to all thou diligent friends to help us making Shopware better and better with each pull request!
```suggestion
Thanks to all diligent friends for helping us make Shopware better and better with each pull request!
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +## More ressources:
```suggestion
## More resources:
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +* Study a detailled [diff on Github](https://github.com/shopware/shopware/compare/v6.5.7.0...v6.5.6.2) to the former version
```suggestion
* [Detailed diff on Github](https://github.com/shopware/shopware/compare/v6.5.7.0...v6.5.6.2) to the former version
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +* See the [changelog](https://github.com/shopware/shopware/blob/v6.5.7.0/CHANGELOG.md) for this version on GitHub
```suggestion
* [Changelog on GitHub](https://github.com/shopware/shopware/blob/v6.5.7.0/CHANGELOG.md) for this version.
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +* Read the marketing blog post at [https://www.shopware.com/en/news/shopware-6-release-news-november-2023/](https://www.shopware.com/en/news/shopware-6-release-news-november-2023/)
```suggestion
* [Marketing blog post](https://www.shopware.com/en/news/shopware-6-release-news-november-2023/)
```

2023-11-16 17:46 UTC, sushmangupta commented on src/6.5.7.x/6.5.7.0.md
> +Discuss about decisions, bugs you might stumble upon etc in our [community slack](https://slack.shopware.com). See you there ;)
```suggestion
Discuss about decisions, bugs you might stumble upon, etc in our [community slack](https://slack.shopware.com). See you there ;)
```

2023-11-17 10:13 UTC, kermie commented on src/6.5.6.x/6.5.6.0.md
> +* from now on, Shopware needs the PHP library `bcmath` in order to function properly. You may install it with `$ apt install php-bcmath` on your linux machine. We already added it to our [system requ
that was an example only ;)

2023-11-17 10:20 UTC, kermie commented on src/6.5.7.x/6.5.7.0.md
> +## Abstract
It shall rather be an abstract than an introduction a la "this patch release contains two bug fixes, we didn't touch the storefront at all". We can also call it _synopsis_ if _abstract_ is misleading.

2023-11-17 10:24 UTC, kermie commented on src/6.5.7.x/6.5.7.0.md
> +# Release notes Shopware 6.5.7.0
Right, they call it like that: https://www.shopware.com/en/news/shopware-6-release-news-october-2023/. But, to be very honest: as a developer, I am more interested in the version number, don't care the season when it was published.

2023-11-17 14:42 UTC, bojanrajh commented on src/6.5.7.x/6.5.7.0.md
> +# Release notes Shopware 6.5.7.0
I'm with Marco on this one. On top of that, we have multiple releases every month - https://www.shopware.com/en/changelog/

2023-11-20 14:19 UTC, merged